---
language: node_js
node_js:
  - 8

sudo: false

sudo: required

cache:
  directories:
  - $HOME/.npm

install:
  - npm install --prod

script:
  - npm test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then hexo deploy; fi
