---
language: node_js
node_js:
  - 8

sudo: false
dist: trusty

branches:
  only:
    - master
    - "/[Vv]?\\d+\\.\\d+\\.\\d+/"

cache:
  directories:
  - $HOME/.npm

jobs:
  include:
    - stage: Testing
    - stage: Deployment
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: hexo deploy
        on:
          tags: true
