version: 0.1

phases:
  install:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH=$HOME/.yarn/bin:$PATH
  pre_build:
    commands:
      - yarn global install hexo-cli
      - yarn install --prod
  build:
    commands:
      - echo Build started on `date`
      - hexo deploy
  post_build:
    commands:
      - echo Build completed on `date`
