version: 0.1

phases:
  install:
    commands:
      - npm i -g hexo-cli
  pre_build:
    commands:
      - npm install --prod
  build:
    commands:
      - echo Build started on `date`
      - npm test
      - hexo deploy
  post_build:
    commands:
      - echo Build completed on `date`
